version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.10'
  jobs:
    post_create_environment:
      - echo $READTHEDOCS_VIRTUALENV_PATH
      - curl -sSL https://install.python-poetry.org | python3 -
      - /home/docs/.local/bin/poetry config virtualenvs.create false
    post_install:
      - "$READTHEDOCS_VIRTUALENV_PATH/bin/activate"
      - /home/docs/.local/bin/poetry install --with docs

sphinx:
   configuration: docs/source/conf.py
   fail_on_warning: true

# python:
#   install:
#     - requirements: docs/requirements.txt
