version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.10'
  jobs:
    post_create_environment:
      - curl -sSL https://install.python-poetry.org | python3 -
      - echo $PATH
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with docs

sphinx:
   configuration: docs/source/conf.py
   fail_on_warning: true

# python:
#   install:
#     - requirements: docs/requirements.txt
